# Run Jupyter inside a container
jupyter:
  user: jupyter
  working_dir: /home/jupyter/working
  ports: ["8888:8888"]
  volumes: [$PWD:/home/jupyter]
  image: gcr.io/kaggle-images/python
  command: jupyter lab --ip="0.0.0.0"
